---
- name: Deploy Fail2Ban jail.local
  become: true
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban

- name: Ensure Fail2Ban service is enabled and running
  become: true
  service:
    name: fail2ban
    enabled: yes
    state: started
