---
# Default variables for docker
docker_edition: 'ce'
docker_packages:
  - "docker-{{ docker_edition }}"
  - "docker-{{ docker_edition }}-cli"
  - "docker-{{ docker_edition }}-rootless-extras"
docker_packages_state: present

docker_install_compose_plugin: true
docker_compose_package: docker-compose-plugin
docker_compose_package_state: present

docker_service_manage: true
docker_service_state: started
docker_service_enabled: true

docker_users:
  - "{{ ansible_user_id }}"
