---
- name: Deploy all cron wrapper scripts
  become: true
  template:
    src:  "{{ item | basename }}"
    dest: "{{ cron_scripts_path }}/{{ item | basename | regex_replace('\\.j2$','') }}"
    mode: '0755'
  loop: "{{ lookup('fileglob', role_path + '/templates/*.sh.j2', wantlist=True) }}"
  loop_control:
    label: "{{ item | basename }}"
