---
- name: Check if htpasswd file exists
  stat:
    path: "{{ docker_dir }}/Registry/data/registry/auth/htpasswd"
  register: htpasswd_stat
  when: docker_dir is defined

- name: Run generate_htpasswd.sh if htpasswd is missing
  become: true
  command: "./generate_htpasswd.sh"
  args:
    chdir: "{{ docker_dir }}/Registry"
  when:
    - docker_dir is defined
    - not htpasswd_stat.stat.exists
